name: Deploy to staging server
on: 
  pull_request:
    branches:
      - dev

jobs:
  deploy_to_staging: 
    name: deploy webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.ORG_EMAIL}}